import { randomUUID } from "node:crypto";
import { join, extname, normalize, sep } from "node:path";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { Injectable, NotFoundException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";

export interface StoredFile {
  /** Relative path under STORAGE_LOCAL_PATH - what gets persisted to the DB. */
  key: string;
  originalName: string;
  mimeType: string;
  size: number;
}

/**
 * Generic file storage, local-disk only for now (matches STORAGE_DRIVER=local
 * in env.validation.ts - the only value that schema currently allows). Any
 * feature that needs to persist an uploaded file goes through this rather
 * than touching the filesystem directly - submissions upload is the first
 * consumer, more will follow (reports, branding, etc.).
 */
@Injectable()
export class StorageService {
  private readonly root: string;

  constructor(private readonly config: ConfigService) {
    this.root = this.config.get<string>("STORAGE_LOCAL_PATH", "./storage");
  }

  async save(subdir: string, file: Express.Multer.File): Promise<StoredFile> {
    const dir = join(this.root, subdir);
    await mkdir(dir, { recursive: true });

    const filename = `${randomUUID()}${extname(file.originalname)}`;
    const key = join(subdir, filename);
    await writeFile(join(this.root, key), file.buffer);

    return {
      key,
      originalName: file.originalname,
      mimeType: file.mimetype,
      size: file.size,
    };
  }

  async read(key: string): Promise<Buffer> {
    try {
      return await readFile(this.resolveSafe(key));
    } catch {
      throw new NotFoundException("File not found");
    }
  }

  async delete(key: string): Promise<void> {
    await unlink(this.resolveSafe(key)).catch(() => undefined);
  }

  /**
   * Resolves a stored key to an absolute path, rejecting anything that
   * would escape the storage root (e.g. a key containing "../") - keys are
   * only ever generated by save() above, but this guards against a
   * corrupted/tampered value being read back later.
   */
  private resolveSafe(key: string): string {
    const resolvedRoot = normalize(this.root + sep);
    const resolved = normalize(join(this.root, key));
    if (!resolved.startsWith(resolvedRoot)) {
      throw new NotFoundException("File not found");
    }
    return resolved;
  }
}
